name: Bithumb interface build action
on:
  push:
    branches:
      - lijie/test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install node modules
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
        env:
          CI: false

      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build
        env:
          CI: false
      
      - name: Compress
      - run: tar -zcvf clover.tar.gz ./build/chrome
          
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: clover.tar.gz application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
